[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
name = "pytest-install"
version = "0.1.0"

[tool.hatch.envs.hatch-test]
dependencies = [
    "pytest",
    "build",
    "uv",
    "installer",
]
